<?php
const MSG_REGISTER_SUCCESS = 1;
const MSG_REGISTER_FAILURE = 2;
const MSG_REGISTER_DISABLED = 3;
const MSG_REGISTER_NOSPACE = 4;
const MSG_REGISTER_UNKNOWN = 5;
const MSG_UNREGISTER_SUCCESS = 6;
const MSG_UNREGISTER_UNKNOWN = 7;
const MSG_UNREGISTER_DISABLED = 8;